### ISSUE TITLE
Error when running the 1.16.5 installer on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by onthetrail** [ablazingeboy/FoliClientInstaller#7]
When I run the 1.16.5 installer from the terminal (./FoliClientInstaller-Linux), it gives me the error 

"[2540] Error loading Python lib '/tmp/_MEIVnMPxV/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/_MEIVnMPxV/libpython3.9.so.1.0)"

I also tried double clicking the file to run in the file manager but it said "There is no application installed for shared library files".

**Comment by magmaus3** [comment]
Have you tried to run it from the source? (`python3 FoliClientInstaller.py`) You can also download the source zip/tar.gz from releases tab.

**Comment by onthetrail** [comment]
No, but I just tried and it worked thank you! Does this work for the 1.17 installer too?

**Comment by magmaus3** [comment]
I think so.

**Comment by ablazingeboy** [comment]
Sorry I didn't see this earlier, yeah the compatibility of the Linux binaries can be very hit or miss, I'll look into possibly distributing as an AppImage for future releases. As vXtrenius said above, the best move is to run the python source.
